name: ela
channels:
  - conda-forge
  - conda
dependencies: 
  - cartopy=0.17.0
  - rasterio=1.0.24
  - pandas=0.25.0
  - nltk=3.4.4
  - numpy=1.17.0
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - matplotlib=3.1.1
  - matplotlib-base=3.1.1
  - mayavi=4.7.1
  - vtk=8.2.0
  - cython=0.29.13
  - wordcloud=1.5.0
  - pyqt=5.9.2
  - codecov=2.0.15
  - geopandas=0.5.1
  - pytest=5.0.1
  - pytest-cov=2.7.1
  # Optional:
  # - jupyter=1.0.0
  # - jupyterlab=1.0.2
  # - ipywidgets=7.5.0
  # and below are other pinned versions that may be useful if the build breaks down the track.
  # pinned as UT passing on 20190811
  # - python=3.7.3
  # - _libgcc_mutex=0.1
  # - affine=2.2.2
  # - apptools=4.4.0
  # - asn1crypto=0.24.0
  # - atomicwrites=1.3.0
  # - attrs=19.1.0
  # - boost-cpp=1.70.0
  # - bzip2=1.0.8
  # - ca-certificates=2019.6.16
  # - cairo=1.16.0
  # - certifi=2019.6.16
  # - cffi=1.12.3
  # - cfitsio=3.470
  # - chardet=3.0.4
  # - click=7.0
  # - click-plugins=1.1.1
  # - cligj=0.5.0
  # - configobj=5.0.6
  # - coverage=4.5.4
  # - cryptography=2.7
  # - curl=7.65.3
  # - cycler=0.10.0
  # - dbus=1.13.6
  # - envisage=4.7.2
  # - expat=2.2.5
  # - fiona=1.8.6
  # - fontconfig=2.13.1
  # - freetype=2.10.0
  # - freexl=1.0.5
  # - future=0.17.1
  # - gdal=2.4.1
  # - geos=3.7.2
  # - geotiff=1.4.3
  # - gettext=0.19.8.1
  # - giflib=5.1.7
  # - glib=2.58.3
  # - gst-plugins-base=1.14.5
  # - gstreamer=1.14.5
  # - hdf4=4.2.13
  # - hdf5=1.10.5
  # - icu=64.2
  # - idna=2.8
  # - importlib_metadata=0.18
  # - joblib=0.13.2
  # - jpeg=9c
  # - json-c=0.13.1
  # - jsoncpp=1.8.4
  # - kealib=1.4.10
  # - kiwisolver=1.1.0
  # - krb5=1.16.3
  # - libblas=3.8.0
  # - libcblas=3.8.0
  # - libcurl=7.65.3
  # - libdap4=3.20.2
  # - libedit=3.1.20170329
  # - libffi=3.2.1
  # - libgcc-ng=9.1.0
  # - libgdal=2.4.1
  # - libgfortran-ng=7.3.0
  # - libiconv=1.15
  # - libkml=1.3.0
  # - liblapack=3.8.0
  # - libnetcdf=4.6.2
  # - libopenblas=0.3.6
  # - libpng=1.6.37
  # - libpq=11.5
  # - libspatialindex=1.9.0
  # - libspatialite=4.3.0a
  # - libssh2=1.8.2
  # - libstdcxx-ng=9.1.0
  # - libtiff=4.0.10
  # - libuuid=2.32.1
  # - libxcb=1.13
  # - libxml2=2.9.9
  # - lz4-c=1.8.3
  # - more-itertools=7.2.0
  # - munch=2.3.2
  # - ncurses=6.1
  # - olefile=0.46
  # - openjpeg=2.3.1
  # - openssl=1.1.1c
  # - owslib=0.18.0
  # - packaging=19.0
  # - pcre=8.41
  # - pillow=6.1.0
  # - pixman=0.38.0
  # - pluggy=0.12.0
  # - poppler=0.67.0
  # - poppler-data=0.4.9
  # - postgresql=11.5
  # - proj4=5.2.0
  # - pthread-stubs=0.4
  # - py=1.8.0
  # - pycparser=2.19
  # - pyepsg=0.4.0
  # - pyface=6.1.2
  # - pygments=2.4.2
  # - pykdtree=1.3.1
  # - pyopenssl=19.0.0
  # - pyparsing=2.4.2
  # - pyproj=1.9.6
  # - pyshp=2.1.0
  # - pysocks=1.7.0
  # - python=3.7.3
  # - python-dateutil=2.8.0
  # - pytz=2019.2
  # - qt=5.9.7
  # - readline=8.0
  # - requests=2.22.0
  # - rtree=0.8.3
  # - setuptools=41.0.1
  # - shapely=1.6.4
  # - sip=4.19.8
  # - six=1.12.0
  # - snuggs=1.4.6
  # - sqlite=3.29.0
  # - striplog=0.7.3
  # - tbb=2019.7
  # - tk=8.6.9
  # - tornado=6.0.3
  # - traits=5.1.2
  # - traitsui=6.1.2
  # - tzcode=2019a
  # - urllib3=1.25.3
  # - wcwidth=0.1.7
  # - wheel=0.33.4
  # - xerces-c=3.2.2
  # - xorg-kbproto=1.0.7
  # - xorg-libice=1.0.10
  # - xorg-libsm=1.2.3
  # - xorg-libx11=1.6.8
  # - xorg-libxau=1.0.9
  # - xorg-libxdmcp=1.1.3
  # - xorg-libxext=1.3.4
  # - xorg-libxrender=0.9.10
  # - xorg-libxt=1.2.0
  # - xorg-renderproto=0.11.1
  # - xorg-xextproto=7.3.0
  # - xorg-xproto=7.0.31
  # - xz=5.2.4
  # - zipp=0.5.2
  # - zlib=1.2.11
  # - zstd=1.4.0
  - pip
  - pip:
    #  - mayavi==4.7.1 # no need now that suitable conda pkg
    - git+https://github.com/jmp75/striplog@master#egg=striplog
    - ela
